NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

ACCOUNTS=[
    "GAA2STTQ5UYRSNNSWS5R6FAV5SLB2THPPBYGV5MZ3DH5LDN5YAODVENO",
    "GAUCEMTLRZ6G3YJWUMRNFCWJEFXVPDIYQG6S3R6VCLSRBIIQBVLPZ53D",
]

[DOCUMENTATION]
ORG_URL="https://mayocoin.rf.gd/"
ORG_LOGO="https://mayocoin.rf.gd/mayocoinsmall.png"
ORG_DESCRIPTION="The Most Delicious Meme Coin on Stellar"
ORG_OFFICIAL_EMAIL="realmayocoin@gmail.com"

[[CURRENCIES]]
code="MAYO"
issuer="GAA2STTQ5UYRSNNSWS5R6FAV5SLB2THPPBYGV5MZ3DH5LDN5YAODVENO"
display_decimals=6
name="MayoCoin"
desc="The Most Delicious Meme Coin on Stellar"
conditions="There will be only 18778580398 MayoCoins in existence."
image="https://mayocoin.rf.gd/mayocoinsmall.png"
fixed_number=18778580398

