NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

ACCOUNTS=[
    "GC5TLOYRAEXMHSJ5H3CZYZVT22IZSDANO2COJLSCSVMZZRS7QUPXM6QT",
    "GAUCEMTLRZ6G3YJWUMRNFCWJEFXVPDIYQG6S3R6VCLSRBIIQBVLPZ53D",
]

[DOCUMENTATION]
ORG_URL="https://remarkablemayonaise.github.io/"
ORG_LOGO="https://remarkablemayonaise.github.io/mayocoinsmall.png"
ORG_DESCRIPTION="The Most Delicious Meme Coin on Stellar"
ORG_OFFICIAL_EMAIL="realmayocoin@gmail.com"

[[CURRENCIES]]
code="MayoCoin"
issuer="GC5TLOYRAEXMHSJ5H3CZYZVT22IZSDANO2COJLSCSVMZZRS7QUPXM6QT"
display_decimals=6
name="MayoCoin"
desc="The Most Delicious Meme Coin on Stellar"
conditions="There will be only 18778580398 MayoCoins in existence."
image="https://remarkablemayonaise.github.io/mayocoinsmall.png"
fixed_number=18778580398
